name: Run tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Run tests'
        run: |
          pytest tests -v
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GROQ_MODEL_NAME: ${{ secrets.GROQ_MODEL_NAME }}
          LOCAL_DEVELOPMENT: ${{ secrets.LOCAL_DEVELOPMENT }}
